package models

// StartWorkoutRequest opens a guided session for one day of a training plan.
// ClientSessionID is optional and generated by the app when the session starts
// offline: it makes the start idempotent, so the queue can replay it after a
// timeout without creating a second workout.
type StartWorkoutRequest struct {
	TrainingPlanDayID int64  `json:"training_plan_day_id"`
	ClientSessionID   string `json:"client_session_id,omitempty"`
}

// CompleteSetRequest records one finished series. Weight is kept on the series
// itself for history, and echoed onto the plan exercise as next time's suggestion.
//
// ClientSetID is optional and minted by the app before the request goes out.
// It makes the write idempotent: if the connection drops after the server
// commits but before the response arrives, the offline queue replays the same
// POST, and without this key the replay would be indistinguishable from a real
// extra series (set_number is derived server-side from a COUNT, so a replay
// just looks like "the next legitimate series" and gets inserted again).
type CompleteSetRequest struct {
	TrainingPlanExerciseID *int64  `json:"training_plan_exercise_id"`
	ExerciseName           string  `json:"exercise_name"`
	SetNumber              int     `json:"set_number"`
	Reps                   int     `json:"reps"`
	WeightKg               float64 `json:"weight_kg"`
	TrackingType           string  `json:"tracking_type"`
	DurationSeconds        *int    `json:"duration_seconds"`
	ClientSetID            string  `json:"client_set_id,omitempty"`
}

// CompleteWorkoutRequest closes a session in one shot from a checklist, topping
// each exercise up to the number of series the user marked as done. It serves
// both the quick log (never entered the guided mode) and finishing a guided
// session early with whatever is already ticked.
type CompleteWorkoutRequest struct {
	Notes     string                    `json:"notes"`
	Exercises []CompleteWorkoutExercise `json:"exercises"`
}

type CompleteWorkoutExercise struct {
	TrainingPlanExerciseID int64   `json:"training_plan_exercise_id"`
	SetsDone               int     `json:"sets_done"`
	WeightKg               float64 `json:"weight_kg"`
}

// ActiveWorkout is everything the guided screen needs to render or resume:
// the open workout, the planned exercises, and the series already done.
type ActiveWorkout struct {
	Workout   Workout                `json:"workout"`
	PlanID    *int64                 `json:"plan_id,omitempty"`
	DayName   string                 `json:"day_name"`
	Exercises []TrainingPlanExercise `json:"exercises"`
}

// TrainingSettings holds the guided session preferences shown in the settings screen.
type TrainingSettings struct {
	CountdownSeconds int  `json:"countdown_seconds"`
	VibrationEnabled bool `json:"vibration_enabled"`
	AutoAdvance      bool `json:"auto_advance"`
}
